name: Terraform CI

description: On push to main branch, format and validate Terraform changes

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt  
      - name: Terraform Validate
        run: terraform validate